# Generated by Django 4.2.6 on 2023-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_remove_chat_chat_username_chat_chat_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_username",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
