# Generated by Django 4.2.6 on 2023-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_chat_chat_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="name",
            field=models.CharField(default="User", max_length=200),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(max_length=50),
        ),
    ]
