# Generated by Django 4.2.6 on 2023-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_message_name_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
